Style/Documentation:
  Enabled: false

Style/ClassVars:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true